# Generated by Django 6.0.4 on 2026-05-03 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combos', '0002_initial'),
        ('courses', '0001_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersaveditems',
            name='combo',
            field=models.ForeignKey(blank=True, help_text="Populated when item_type='combo'. Null otherwise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='combos.combo'),
        ),
        migrations.AddField(
            model_name='usersaveditems',
            name='course',
            field=models.ForeignKey(blank=True, help_text="Populated when item_type='course'. Null otherwise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='courses.course'),
        ),
        migrations.AddField(
            model_name='usersaveditems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'status'], name='idx_progress_user_status'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='usersaveditems',
            index=models.Index(fields=['user', 'item_type'], name='idx_saved_user_type'),
        ),
        migrations.AddConstraint(
            model_name='usersaveditems',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'course')), fields=('user', 'course'), name='unique_saved_course_per_user'),
        ),
        migrations.AddConstraint(
            model_name='usersaveditems',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'combo')), fields=('user', 'combo'), name='unique_saved_combo_per_user'),
        ),
    ]
