# Generated by Django 6.0.4 on 2026-05-03 02:24

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier. Auto-generated on creation.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this record.')),
                ('created_by_type', models.CharField(choices=[('admin', 'Admin'), ('system', 'System'), ('user', 'User')], default='user', help_text='Whether this Combo was created by admin, system, or a user.', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.TextField(blank=True, default='', help_text='Short summary shown in combo cards.', max_length=300)),
                ('full_description', models.TextField(blank=True, default='')),
                ('overview', models.TextField(blank=True, default='', help_text='High-level overview of what this learning path covers.')),
                ('who_is_this_for', models.TextField(blank=True, default='', help_text='Description of the intended learner audience.')),
                ('learning_outcomes', models.JSONField(blank=True, default=list, help_text='What learners will be able to do after completing this Combo.')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Knowledge or skills required before starting this Combo.')),
                ('skills_gained', models.JSONField(blank=True, default=list, help_text='Specific skills acquired upon completion.')),
                ('learning_path_explanation', models.TextField(blank=True, default='', help_text='Explanation of why the courses are ordered the way they are.')),
                ('category', models.CharField(blank=True, default='', help_text='Primary STEM category for this Combo.', max_length=50)),
                ('sub_category', models.CharField(blank=True, default='', max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Mixed', 'Mixed')], default='Beginner', max_length=20)),
                ('recommended_age', models.CharField(choices=[('Kids', 'Kids (under 13)'), ('Teens', 'Teens (13–17)'), ('Adults', 'Adults (18--)'), ('All Ages', 'All Ages')], default='All Ages', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('estimated_weeks', models.PositiveIntegerField(default=0, help_text='Estimated total weeks to complete this Combo.')),
                ('estimated_hours_per_week', models.PositiveIntegerField(default=0, help_text='Recommended hours per week to complete within the estimated timeframe.')),
                ('is_public', models.BooleanField(default=False, help_text='User-created Combos are private by default. Must be explicitly shared.')),
                ('is_featured', models.BooleanField(default=False, help_text='Admin-featured Combos appear prominently on the platform.')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'db_table': 'combos',
            },
        ),
        migrations.CreateModel(
            name='ComboCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier. Auto-generated on creation.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this record.')),
                ('order', models.PositiveIntegerField(help_text='1-indexed position of this course in the Combo.')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this course is mandatory within the Combo.')),
                ('note', models.TextField(blank=True, default='', help_text='Curator note explaining why this course is at this position.')),
            ],
            options={
                'verbose_name': 'Combo Course',
                'verbose_name_plural': 'Combo Courses',
                'db_table': 'combo_courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComboRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier. Auto-generated on creation.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this record.')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (lowest) to 5 (highest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, default='', help_text='Optional written review alongside the star rating.', max_length=1000)),
            ],
            options={
                'verbose_name': 'Combo Rating',
                'verbose_name_plural': 'Combo Ratings',
                'db_table': 'combo_ratings',
            },
        ),
    ]
