# Generated by Django 6.0.4 on 2026-05-03 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combos', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='The user who created this Combo. Null for admin/system-created Combos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combocourse',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_courses', to='combos.combo'),
        ),
        migrations.AddField(
            model_name='combocourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_courses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='combo',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='combos', through='combos.ComboCourse', to='courses.course'),
        ),
        migrations.AddField(
            model_name='comborating',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='combos.combo'),
        ),
        migrations.AddField(
            model_name='comborating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='combocourse',
            unique_together={('combo', 'order')},
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['is_public'], name='idx_combo_public'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['is_featured'], name='idx_combo_featured'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['category'], name='idx_combo_category'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['created_by_type'], name='idx_combo_creator_type'),
        ),
        migrations.AlterUniqueTogether(
            name='comborating',
            unique_together={('combo', 'user')},
        ),
    ]
