# Generated by Django 6.0.4 on 2026-05-03 02:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier. Auto-generated on creation.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this record.')),
                ('title', models.CharField(help_text='Course title as displayed on the platform.', max_length=500)),
                ('short_description', models.TextField(blank=True, default='', help_text='Short summary shown in course cards (max 500 chars).', max_length=300)),
                ('full_description', models.TextField(blank=True, default='', help_text='Full course description shown on the detail page.')),
                ('learning_outcomes', models.JSONField(blank=True, default=list, help_text="List of what learners will achieve e.g. ['Understand variables', 'Write loops'].")),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='List of prerequisite knowledge or courses.')),
                ('provider', models.CharField(choices=[('YouTube', 'YouTube'), ('freeCodeCamp', 'freeCodeCamp'), ('MIT OCW', 'MIT OpenCourseWare'), ('OpenStax', 'OpenStax'), ('CK-12', 'CK-12'), ('Khan Academy', 'Khan Academy')], help_text='The external platform or institution that created this course.', max_length=50)),
                ('provider_type', models.CharField(choices=[('video_platform', 'Video Platform'), ('learning_platform', 'Learning Platform'), ('university', 'University'), ('open_textbook', 'Open Textbook')], help_text='Category of provider.', max_length=50)),
                ('source_url', models.URLField(help_text='Canonical URL to the course on the source platform.')),
                ('instructor', models.CharField(blank=True, default='', help_text='Name of the course instructor or creator.', max_length=200)),
                ('category', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Natural Sciences', 'Natural Sciences'), ('Engineering', 'Engineering'), ('Technology & Applied Skills', 'Technology & Applied Skills'), ('STEM Foundations', 'STEM Foundations')], help_text='Top-level STEM category. Drives filtering and Combo grouping.', max_length=50)),
                ('sub_category', models.CharField(blank=True, default='', help_text='More specific sub-category within the top-level category.', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Free-form tags for search and filtering e.g. ['python', 'loops', 'beginner'].")),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('age_group', models.CharField(choices=[('Kids', 'Kids (under 13)'), ('Teens', 'Teens (13–17)'), ('Adults', 'Adults (18--)')], default='Adults', max_length=10)),
                ('language', models.CharField(default='en', help_text="ISO 639-1 language code e.g. 'en', 'fr'.", max_length=10)),
                ('format', models.CharField(choices=[('Video', 'Video'), ('Text', 'Text'), ('Interactive', 'Interactive')], default='Video', max_length=20)),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Total course duration in hours.')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Remaining minutes beyond the total hours.')),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='External URL to course thumbnail. No local storage at MVP.')),
                ('is_free', models.BooleanField(default=True, help_text='All MVP content is free. Flag reserved for future paid content.')),
                ('certificate_available', models.BooleanField(default=False, help_text='Whether the source platform offers a completion certificate.')),
                ('rating_average', models.FloatField(default=0.0, help_text='Average rating pulled from the source platform.')),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Number of ratings on the source platform.')),
                ('source_metadata', models.JSONField(default=dict, help_text='Original data from the ingestion source. Keys: original_title, original_description, api_source, external_id. Never modified after ingestion. Enables reprocessing.')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL tsvector for full-text search. Auto-updated on save.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive courses are hidden from public listings but retained in the DB.')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'indexes': [models.Index(fields=['provider'], name='idx_course_provider'), models.Index(fields=['category'], name='idx_course_category'), models.Index(fields=['level'], name='idx_course_level'), models.Index(fields=['age_group'], name='idx_course_age_group'), models.Index(fields=['is_active'], name='idx_course_active'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_course_search_vector')],
            },
        ),
    ]
