# Generated by Django 6.0.4 on 2026-05-03 02:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier. Auto-generated on creation.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this record.')),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('freecodecamp', 'freeCodeCamp'), ('mit_ocw', 'MIT OpenCourseWare'), ('openstax', 'OpenStax'), ('ck12', 'CK-12')], help_text='Which external source this ingestion run pulled from.', max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial Success'), ('fallback', 'Fallback Triggered'), ('failed', 'Failed')], default='started', help_text='Outcome of the ingestion run.', max_length=10)),
                ('courses_fetched', models.PositiveIntegerField(default=0, help_text='Total raw courses retrieved from the source.')),
                ('courses_created', models.PositiveIntegerField(default=0, help_text='New courses written to the database in this run.')),
                ('courses_updated', models.PositiveIntegerField(default=0, help_text='Existing courses updated in this run.')),
                ('courses_skipped', models.PositiveIntegerField(default=0, help_text='Courses skipped (duplicate, invalid, or filtered out).')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if status is FAILED or PARTIAL.')),
                ('fallback_triggered', models.BooleanField(default=False, help_text='True when a fallback path was used during this run. Rule 11: 3 consecutive or 5 within 24h triggers investigation.')),
                ('fallback_reason', models.TextField(blank=True, default='', help_text='Description of what caused the fallback, if fallback_triggered=True.')),
                ('started_at', models.DateTimeField(help_text='When this ingestion run began.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this ingestion run finished. Null if still running or failed mid-run.', null=True)),
            ],
            options={
                'verbose_name': 'Ingestion Log',
                'verbose_name_plural': 'Ingestion Logs',
                'db_table': 'ingestion_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='idx_ingestion_source_status'), models.Index(fields=['started_at'], name='idx_ingestion_started_at'), models.Index(fields=['fallback_triggered'], name='idx_ingestion_fallback')],
            },
        ),
    ]
