# Generated by Django 6.0.4 on 2026-05-03 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier. Auto-generated on creation.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this record.')),
                ('email', models.EmailField(help_text='Primary identifier. Used for login and notifications.', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive users cannot log in. Use this instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text='Staff users can access the Django admin panel.')),
                ('is_email_verified', models.BooleanField(default=False, help_text='True once the user has confirmed their email address.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier. Auto-generated on creation.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this record.')),
                ('display_name', models.CharField(blank=True, default='', help_text='Optional display name shown on the platform.', max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='', help_text="External URL to the user's avatar image. Stored as URL only (no local storage at MVP).")),
                ('age_group', models.CharField(choices=[('Kids', 'Kids (under 13)'), ('Teens', 'Teens (13–17)'), ('Adults', 'Adults (18+)')], default='Adults', help_text='Used to filter and recommend age-appropriate content.', max_length=10)),
                ('bio', models.TextField(blank=True, default='', help_text='Short user bio, optional.', max_length=500)),
                ('interests', models.JSONField(blank=True, default=list, help_text="List of STEM category interests e.g. ['Computer Science', 'Mathematics'].")),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
