# Generated by Django 6.0.4 on 2026-05-03 02:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier. Auto-generated on creation.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this record.')),
                ('event_name', models.CharField(help_text="Event name constant from analytics/events.py e.g. 'user_signed_up'.", max_length=100)),
                ('user_id', models.CharField(blank=True, default='', help_text='UUID of the user who triggered this event. Empty for anonymous events.', max_length=50)),
                ('properties', models.JSONField(default=dict, help_text='Event-specific payload. Shape varies by event_name.')),
                ('context', models.JSONField(default=dict, help_text='Platform context: platform, device, country.')),
                ('sent_to_posthog', models.BooleanField(default=False, help_text='True once successfully delivered to PostHog.')),
                ('posthog_error', models.TextField(blank=True, default='', help_text='Error message if PostHog delivery failed.')),
                ('fired_at', models.DateTimeField(auto_now_add=True, help_text='When this event was first recorded locally.')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'db_table': 'event_logs',
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['event_name'], name='idx_event_name'), models.Index(fields=['user_id'], name='idx_event_user'), models.Index(fields=['sent_to_posthog'], name='idx_event_sent'), models.Index(fields=['fired_at'], name='idx_event_fired_at')],
            },
        ),
    ]
